service: at-encpdf

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::arcotechstudoslmsfiles"
  lambdaHashingVersion: 20201221


functions:
  encrypt:
    handler: encrypt.handle
    environment:
      bucket: arcotechstudoslmsfiles
      hash: "%252s%¨3-"
      pdftronkey: "demo:1630507513016:78fce14403000000007b2248cb7b18a79ea8aea117e5f1c5e5b33d2214"
    events:
      - s3:
          bucket: arcotechstudoslmsfiles
          event: s3:ObjectCreated:*
          rules:
            - prefix: lms/uploads/
            - suffix: .pdf
          existing: true #Use this attribute if Bucket already created